# MovieAnalysis

## Описание проекта
Проект представляет собой автоматизированный ETL-пайплайн для работы с кинематографическими данными. Основной фокус направлен на слияние большого массива зрительских рейтингов с финансовой аналитикой, извлеченной с платформы TMDB посредством веб-скрейпинга.

В этом отчете представлены итоговые аналитические витрины, готовые для дальнейшего исследования и бизнес-анализа.

In [33]:
import sqlite3
import pandas as pd

DB_PATH = '../dwh.sqlite'

def query_sql(query):
    """A helper function for quickly reading marts in a pandas DataFrame"""
    with sqlite3.connect(DB_PATH) as conn:
        return pd.read_sql(query, conn)

### Самые продуктивные режиссеры индустрии

В этой витрине мы оцениваем режиссеров не по кассовым сборам или оценкам критиков, а по их **кинематографической плодовитости** — количеству картин, представленных в нашем датасете.

In [34]:
query_directors = "SELECT * FROM mart_top_directors LIMIT 10"
df_directors = query_sql(query_directors)

df_directors

          director  movies_count
0  Martin Scorsese             2
1      Zhang Yimou             1
2      Woody Allen             1
3     Wes Anderson             1
4     Victor Salva             1
5     Ulu Grosbard             1
6      Tim Robbins             1
7         Tim Reid             1
8   Terry McMillan             1
9    Terry Gilliam             1

### Финансовые амбиции и риски: Самые дорогие фильмы

Бюджет картины — это прямой показатель ставки, которую делает студия, и уровня принимаемого финансового риска. В этой витрине мы объединяем базовый справочник фильмов с распарсенной статистикой TMDB, чтобы выявить настоящие мега-блокбастеры.

In [35]:
query_expensive = "SELECT * FROM mart_most_expensive LIMIT 10"
df_expensive = query_sql(query_expensive)

df_expensive

                            title  budget
0         Cutthroat Island (1995)  102000
1               Braveheart (1995)   72000
2              Money Train (1995)   68000
3                  Jumanji (1995)   65000
4  American President, The (1995)   62000
5                GoldenEye (1995)   60000
6                     Heat (1995)   60000
7                  Sabrina (1995)   58000
8               Pocahontas (1995)   55000
9                   Casino (1995)   50000

### Финансовая успешность: Лидеры по абсолютной прибыли

Самый дорогой фильм — далеко не всегда самый успешный. В этой витрине мы переходим от оценки затрат к реальной финансовой отдаче, вычисляя чистую разницу между мировыми кассовыми сборами и производственным бюджетом.

In [36]:
query_profitable = "SELECT * FROM mart_most_profitable LIMIT 10"
df_profitable = query_sql(query_profitable)

df_profitable

                                   title  profit
0                       Toy Story (1995)  932301
1            Seven (a.k.a. Se7en) (1995)  294311
2                       GoldenEye (1995)  292194
3                      Pocahontas (1995)  291079
4                            Babe (1995)  224100
5                         Jumanji (1995)  197821
6  Ace Ventura: When Nature Calls (1995)  182385
7  Bridges of Madison County, The (1995)  158000
8                 Dangerous Minds (1995)  156519
9                      Braveheart (1995)  141216

### Эпический размах: Самые продолжительные картины

От финансовых показателей мы переходим к анализу формата. В этой витрине мы исследуем хронометраж фильмов. В эпоху, когда стандарты кинопроката диктуют длительность около двух часов для максимизации количества сеансов, сверхдлинные фильмы представляют особый интерес.

In [37]:
query_longest = "SELECT * FROM mart_longest_movies LIMIT 10"
df_longest = query_sql(query_longest)

df_longest

                                   title  runtime
0                           Nixon (1995)    11520
1                          Casino (1995)    10740
2                      Braveheart (1995)    10680
3                 Misérables, Les (1995)    10500
4                            Heat (1995)    10200
5              Mr. Holland's Opus (1995)     8580
6           Sense and Sensibility (1995)     8160
7  Bridges of Madison County, The (1995)     8100
8                       Assassins (1995)     7920
9                       GoldenEye (1995)     7800

### Плотность бюджета: Стоимость одной минуты фильма

В этой витрине мы не просто берем готовые цифры, а создаем новую, производную метрику — **стоимость одной минуты экранного времени**. Это позволяет оценить «плотность» инвестиций в каждый кадр, независимо от общей продолжительности картины.

In [38]:
query_cost_per_minute = "SELECT * FROM mart_top_cost_per_minute LIMIT 10"
df_cost_per_minute = query_sql(query_cost_per_minute)

df_cost_per_minute

                                title  cost_per_minute
0             Cutthroat Island (1995)            13.71
1                   Pocahontas (1995)            11.32
2                      Jumanji (1995)            10.42
3                  Money Train (1995)            10.30
4                    Fair Game (1995)             9.16
5      American President, The (1995)             9.14
6  Indian in the Cupboard, The (1995)             7.81
7                 Broken Arrow (1996)             7.72
8                    GoldenEye (1995)             7.69
9                      Sabrina (1995)             7.61

### Эффективность инвестиций: Лидеры по показателю ROI

Если абсолютная прибыль показывает общий масштаб заработка, то **ROI (Return on Investment)** демонстрирует истинную финансовую эффективность проекта. Эта метрика отвечает на главный вопрос любого продюсера или инвестора: *какой процент чистой прибыли принес каждый вложенный в производство доллар?*

In [39]:
query_highest_roi = "SELECT * FROM mart_highest_roi LIMIT 10"
df_highest_roi = query_sql(query_highest_roi)

df_highest_roi

                                   title  roi_percentage
0                       Toy Story (1995)         3107.67
1                     Taxi Driver (1976)         1404.16
2               Leaving Las Vegas (1995)         1283.33
3            Seven (a.k.a. Se7en) (1995)          891.85
4                            Babe (1995)          747.00
5           Sense and Sensibility (1995)          741.14
6                          Friday (1995)          706.14
7                 Dangerous Minds (1995)          680.52
8  Bridges of Madison County, The (1995)          658.33
9  Ace Ventura: When Nature Calls (1995)          607.95

### Голливудские катастрофы: Крупнейшие кассовые провалы

Обратная сторона финансового успеха — грандиозные кассовые провалы. В этой витрине мы ищем фильмы, которые принесли студиям максимальные убытки в абсолютном выражении, отнимая итоговые сборы от производственного бюджета.

In [40]:
query_flops = "SELECT * FROM mart_biggest_flops LIMIT 10"
df_flops = query_sql(query_flops)

df_flops

                                title  absolute_loss
0             Cutthroat Island (1995)          86000
1                    Fair Game (1995)          38500
2                  Mary Reilly (1996)          34621
3                        Nixon (1995)          30319
4                 White Squall (1996)          27700
5                 Nick of Time (1995)          24825
6                   Juror, The (1996)          21246
7                    Assassins (1995)          19697
8                        Balto (1995)          19652
9  Dracula: Dead and Loving It (1995)          19228

### Золотая жила Голливуда: Самые прибыльные режиссеры

Эта витрина смещает фокус с единичных картин на оценку долгосрочной коммерческой ценности самих творцов. Мы агрегируем чистую прибыль со всех успешных проектов каждого режиссера, чтобы выявить главных создателей капитала в киноиндустрии.

In [41]:
query_top_earning = "SELECT * FROM mart_top_earning_directors LIMIT 10"
df_top_earning = query_sql(query_top_earning)

df_top_earning

         director  total_profit
0   John Lasseter        932301
1   David Fincher        294311
2     Ian Fleming        292194
3    Mike Gabriel        291079
4    Chris Noonan        224100
5    Joe Johnston        197821
6  Steve Oedekerk        182385
7  Clint Eastwood        158000
8   John N. Smith        156519
9      Mel Gibson        141216

### Историческая динамика: Активность пользователей во времени

В этой витрине мы меняем фокус: от анализа самих картин мы переходим к исследованию поведения аудитории. Оценка временных рядов (Time Series Analysis) — важнейший этап, позволяющий понять, как менялась вовлеченность пользователей платформы с течением времени.

In [42]:
query_ratings_year = "SELECT * FROM mart_ratings_by_year"
df_ratings_year = query_sql(query_ratings_year)

df_ratings_year

   rating_year  ratings_count
0         1996           6040
1         1997           1916
2         1998            507
3         1999           2439
4         2000          10061
5         2001           3922
6         2002           3478
7         2003           4014
8         2004           3279
9         2005           5813
10        2006           4059
11        2007           7114
12        2008           4351
13        2009           4158
14        2010           2301
15        2011           1690
16        2012           4656
17        2013           1664
18        2014           1439
19        2015           6616
20        2016           6703
21        2017           8198
22        2018           6418

### Психология зрителя: Распределение пользовательских оценок

Эта витрина демонстрирует базовую, но фундаментально важную метрику — общее распределение целевой переменной (рейтинга). Мы анализируем, с какой частотой пользователи выбирают ту или иную оценку по шкале от 0.5 до 5.0.

In [43]:
query_distribution = "SELECT * FROM mart_ratings_distribution"
df_distribution = query_sql(query_distribution)

df_distribution

   rating  ratings_count
0     0.5           1370
1     1.0           2811
2     1.5           1791
3     2.0           7551
4     2.5           5550
5     3.0          20047
6     3.5          13136
7     4.0          26818
8     4.5           8551
9     5.0          13211

### Вирусный охват: Самые обсуждаемые фильмы

В этой витрине мы измеряем не качество картины (ее средний балл), а ее **популярность и культурный резонанс**. Количество поставленных оценок выступает надежной метрикой того, насколько фильм известен широкой аудитории.

In [44]:
query_top_rated_count = "SELECT * FROM mart_top_by_num_of_ratings LIMIT 10"
df_top_rated_count = query_sql(query_top_rated_count)

df_top_rated_count

                                       title  num_of_ratings
0                        Forrest Gump (1994)             329
1           Shawshank Redemption, The (1994)             317
2                        Pulp Fiction (1994)             307
3           Silence of the Lambs, The (1991)             279
4                         Matrix, The (1999)             278
5  Star Wars: Episode IV - A New Hope (1977)             251
6                       Jurassic Park (1993)             238
7                          Braveheart (1995)             237
8          Terminator 2: Judgment Day (1991)             224
9                    Schindler's List (1993)             220

### Ловушка средних значений: Топ фильмов по оценкам

В этой витрине мы пытаемся найти величайшие шедевры кинематографа, сортируя базу по наивысшему среднему баллу. Однако этот запрос служит идеальной демонстрацией классической аналитической проблемы — **отсутствия статистической значимости**.

In [45]:
query_top_avg = "SELECT * FROM mart_top_by_avg_rating LIMIT 10"
df_top_avg = query_sql(query_top_avg)

df_top_avg

,title,avg_rating,total_ratings
0,Lamerica (1994),5.0,2
1,Heidi Fleiss: Hollywood Madam (1995),5.0,2
2,"Awfully Big Adventure, An (1995)",5.0,1
3,Live Nude Girls (1995),5.0,1
4,In the Realm of the Senses (Ai no corrida) (1976),5.0,1
5,What Happened Was... (1994),5.0,1
6,"Thin Line Between Love and Hate, A (1996)",5.0,1
7,Denise Calls Up (1995),5.0,1
8,Supercop 2 (Project S) (Chao ji ji hua) (1993),5.0,1
9,Entertaining Angels: The Dorothy Day Story (1996),5.0,1

### Скрытые бриллианты: Поиск недооцененных шедевров

Этот запрос — прямое и элегантное решение проблемы «ловушки средних значений», которую мы наблюдали в предыдущей витрине. Чтобы найти настоящие скрытые шедевры (отличные фильмы, не получившие массовой огласки), мы вводим статистический фильтр.

In [46]:
query_hidden_gems = "SELECT * FROM mart_hidden_gems LIMIT 10"
df_hidden_gems = query_sql(query_hidden_gems)

df_hidden_gems

                                           title  avg_rating  rating_count
0                          Secrets & Lies (1996)        4.59            11
1            Guess Who's Coming to Dinner (1967)        4.55            11
2                          Paths of Glory (1957)        4.54            12
3               Streetcar Named Desire, A (1951)        4.47            20
4               Celebration, The (Festen) (1998)        4.46            12
5                                     Ran (1985)        4.43            15
6                         His Girl Friday (1940)        4.39            14
7          All Quiet on the Western Front (1930)        4.35            10
8  Sunset Blvd. (a.k.a. Sunset Boulevard) (1950)        4.33            27
9                            Hustler, The (1961)        4.33            18

### Анатомия спора: Самые противоречивые фильмы

В этой витрине мы выходим за рамки базовой статистики и создаем **кастомную аналитическую метрику** — коэффициент поляризации. Наша цель — найти картины, которые зрители либо искренне ненавидят, либо превозносят до небес, избегая нейтральных оценок. Коэффициент показывает долю экстремальных баллов (<= 1.5 или >= 4.5) в общей массе отзывов.

In [47]:
query_polarizing = "SELECT * FROM mart_polarizing_movies LIMIT 10"
df_polarizing = query_sql(query_polarizing)

df_polarizing

,title,polarizing_ratio,total_ratings
0,"Shawshank Redemption, The (1994)",0.64,317
1,Schindler's List (1993),0.62,220
2,"Godfather, The (1972)",0.62,192
3,Patton (1970),0.61,33
4,Fight Club (1999),0.61,218
5,Dr. Strangelove or: How I Learned to Stop Worr...,0.59,97
6,Life Is Beautiful (La Vita è bella) (1997),0.59,88
7,Intouchables (2011),0.59,37
8,"Boondock Saints, The (2000)",0.58,43
9,"Departed, The (2006)",0.58,107

### Марафонцы или боты: Поиск аномалий в поведении

Эта витрина переводит фокус с характеристик контента на поведение зрителей. С помощью двухуровневой агрегации мы вычисляем максимальное количество оценок, которое каждый пользователь поставил в течение одних календарных суток.

In [48]:
query_marathoners = "SELECT * FROM mart_top_marathoners LIMIT 10"
df_marathoners = query_sql(query_marathoners)

df_marathoners

   user_id  max_ratings_in_a_day
0      599                  1013
1      610                   866
2      480                   833
3       19                   703
4      177                   605
5      217                   582
6      600                   580
7       91                   575
8      590                   559
9       68                   546